import type { Metadata } from "next";
import { ibmPlexSansKR, nanumHuman } from "./font";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${ibmPlexSansKR.variable} ${nanumHuman.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
